#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Stopping service..."
ynh_systemctl --service="$app" --action=stop

ynh_script_progression "Updating nginx configuration..."
ynh_config_change_url_nginx

ynh_script_progression "Starting service..."
ynh_systemctl --service="$app" --action=start

ynh_script_progression "Change of URL completed for $app"
