#!/bin/bash
source /usr/share/yunohost/helpers
source _common.sh
get_paths_and_settings

ynh_config_remove_nginx
ynh_config_remove_systemd

if [ -n "$install_dir" ] && [ -d "$install_dir" ]; then
    ynh_secure_remove "$install_dir"
fi

if [ -n "$data_dir" ] && [ -d "$data_dir" ]; then
    ynh_secure_remove "$data_dir"
fi

ynh_secure_remove /var/log/x-ui
ynh_secure_remove /etc/x-ui
