#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Removing system configurations..."
ynh_config_remove_nginx
ynh_config_remove_systemd

ynh_safe_rm "/etc/x-ui"

ynh_script_progression "Removal of $app completed"
