#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

ynh_setup_source --dest_dir="$install_dir" --full_replace=1

chmod +x "$install_dir/x-ui"
find "$install_dir/bin" -type f -name "xray-linux-*" -exec chmod +x {} \; 2>/dev/null || true
chown -R "$app:$app" "$install_dir"

ynh_add_systemd_config
ynh_add_nginx_config

ynh_systemctl --service=$app --action=daemon-reload
ynh_systemctl --service=$app --action=restart
